import './globals.css'
import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Plus_Jakarta_Sans } from 'next/font/google'
import { GlobalContextProvider } from './context/store'
import { ThemeProvider } from './Theme_provider'

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kanban Task Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html id="HTML" lang="en">
      <body className={jakarta.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <GlobalContextProvider>
            <main className="flex h-full w-full bg-light-grey dark:bg-very-dark-gray max-sm:flex-col">
              {children}
            </main>
          </GlobalContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
